import { z } from 'zod'

export const PaperMetadataScalarFieldEnumSchema = z.enum([
	'id',
	'arxivId',
	'published',
	'updated',
	'title',
	'abstract',
	'authors',
	'authorIds',
	'absLink',
	'pdfLink',
	'categories',
	'primaryCategory',
	'comments',
	'tags',
	'linkedQuestions',
	'linkedClaims',
	'linkedTopics',
	'linkedDocuments',
	'linkedSnippets',
	'includedInDocuments',
	'roamPage',
	'read',
	'paperDataViewParams',
	'created_at',
	'updated_at',
])
