FROM python:3.12-slim

# Install uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv

WORKDIR /app

# Install deps
COPY pyproject.toml uv.lock* ./
RUN uv sync --frozen --no-cache

# Copy the rest of the app code
COPY . .

# Expose the port
EXPOSE 8000

# Run the app
CMD ["uv", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]